### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by ytaylor** [Adalab/modulo-1-evaluacion-intermedia-JuditAldeguer#1]
Muy buen trabajo @JuditAldeguer!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

- [x] HTML > LINK: El fichero de fuentes debe estar antes que nuestro fichero de estilos para que ningún fichero de estilos externo sobre escriba los nuestros.
- [x] HTML > HEADER: La etiqueta `img` debe tener el atributo `title`.
- [x] HTML > HEADER: Necesitamos al menos una etiqueta `nav`, para definir el menú
- [x] HTML > HEADER: Te sugerimos que uses la etiqueta `ul` para el listado de elementos del menú.
- [x] HTML > HEADER: Los enlaces tienen que tener el atributo `title`.
- [x] HTML > MAIN: Necesitamos al menos una etiqueta h1 para el contenido de "Creando diversidad digital". No utilices un párrafo para cada palabra, ajusta el texto utilizando propiedades css como el ´width ´ del contenedor.
- [x] CSS > FONT-SIZE: El tamaño del h1 en móvil debe ser 30px.
- [x] CSS > FONT-SIZE: El tamaño del h1 en tablet debe ser 40px.
- [x] CSS > PADDING: El padding de los enlaces no debería ser 0. Auméntalo para aumentar el área clickable, pero manteniendo los requisitos del diseño.

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits también tienen que ser en inglés, empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Con cada mejora que hagas, márcala como completada en este issue y su súbela a este repo.
> Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by JuditAldeguer** [comment]
Hola, Yanelis!

Gracias por tu feedback. 
En principio lo he corregido ya todo pero quedo a la espera de tu confirmación y si puedo mejorar algún aspecto más de la web, solo debes decirme!

Espero que estés disfrutando del fin de semana! :)
Hasta mañana

**Comment by ytaylor** [comment]
Hola Judit,

Muy bien trabajo, ya está todo correcto. Muchas Felicidades!
